### ISSUE TITLE
returns error upon translating a word, or doing anything.

### ISSUE THREAD

**Issue by Pikleman101000** [theotarr/latindictionary-io#2]
Raises following error when I try to do anything.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 138, in decline
    TranslWindow(noms, root)
  File "main.py", line 16, in __init__
    trans=dictionary.get_definition("canis")
  File "/home/runner/UDLDeclensionProject/venv/lib/python3.8/site-packages/latindictionary_io/client.py", line 48, in get_definition
    return self.request('GET', 'definition/' + word)
  File "/home/runner/UDLDeclensionProject/venv/lib/python3.8/site-packages/latindictionary_io/client.py", line 14, in request
    raise APIException(response.status_code, response.text)
TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by theotarr** [comment]
Hey! This has been fixed in **v1.0.0**, which is a complete rewrite of the client. The old endpoints were deprecated — the new version uses the updated REST API at `api.latindictionary.io`.

Upgrade with:
```bash
pip install --upgrade latindictionary-io
```

New usage:
```python
from latindictionary_io import Client

client = Client()
print(client.latin_to_english('canis'))
print(client.english_to_latin('dog'))
```

See the [updated README](https://github.com/theotarr/latindictionary-io#readme) for full docs.
